services:
  customer_web:
    build:
      context: .  
      target: development
    ports:
      - "3002:3002"  # Maps host port 3001 to container port 3001
    environment:
      - PORT=3002
      - CHOKIDAR_USEPOLLING=true  # Ensure polling for file changes
    volumes:
      - .:/usr/src/app  # Mount the current directory into the container
      - /usr/src/app/node_modules  # Ensure the container's node_modules is preserved
      - /usr/src/app/build  # Prevent overwriting the build folder
    command: ["npm", "start"]  # Start the React dev server